package Model;

import java.util.ArrayList;


public class Util {

    public ArrayList<Pokemon> initializePokemon() {
        ArrayList<Pokemon> pokemonList = new ArrayList<>();
        pokemonList.add(new Pokemon(1, "Bulbasaur", Types.GRASS, Types.POISON));
        pokemonList.add(new Pokemon(2, "Ivysaur", Types.GRASS, Types.POISON));
        pokemonList.add(new Pokemon(3, "Venusaur", Types.GRASS, Types.POISON));
        pokemonList.add(new Pokemon(4, "Charmander", Types.FIRE));
        pokemonList.add(new Pokemon(5, "Charmeleon", Types.FIRE));
        pokemonList.add(new Pokemon(6, "Charizard", Types.FIRE, Types.FLYING));
        pokemonList.add(new Pokemon(7, "Squirtle", Types.WATER));
        pokemonList.add(new Pokemon(8, "Wartortle", Types.WATER));
        pokemonList.add(new Pokemon(9, "Blastoise", Types.WATER));
        pokemonList.add(new Pokemon(10, "Caterpie", Types.BUG));
        pokemonList.add(new Pokemon(11, "Metapod", Types.BUG));
        pokemonList.add(new Pokemon(12, "Butterfree", Types.BUG, Types.FLYING));
        pokemonList.add(new Pokemon(13, "Weedle", Types.BUG, Types.POISON));
        pokemonList.add(new Pokemon(14, "Kakuna", Types.BUG, Types.POISON));
        pokemonList.add(new Pokemon(15, "Beedrill", Types.BUG, Types.POISON));
        pokemonList.add(new Pokemon(16, "Pidgey", Types.NORMAL, Types.FLYING));
        pokemonList.add(new Pokemon(17, "Pidgeotto", Types.NORMAL, Types.FLYING));
        pokemonList.add(new Pokemon(18, "Pidgeot", Types.NORMAL, Types.FLYING));
        pokemonList.add(new Pokemon(19, "Rattata", Types.NORMAL));
        pokemonList.add(new Pokemon(20, "Raticate", Types.NORMAL));
        pokemonList.add(new Pokemon(21, "Spearow", Types.NORMAL, Types.FLYING));
        pokemonList.add(new Pokemon(22, "Fearow", Types.NORMAL, Types.FLYING));
        pokemonList.add(new Pokemon(23, "Ekans", Types.POISON));
        pokemonList.add(new Pokemon(24, "Arbok", Types.POISON));
        pokemonList.add(new Pokemon(25, "Pikachu", Types.ELECTRIC));
        pokemonList.add(new Pokemon(26, "Raichu", Types.ELECTRIC));
        pokemonList.add(new Pokemon(27, "Sandshrew", Types.GROUND));
        pokemonList.add(new Pokemon(28, "Sandslash", Types.GROUND));
        pokemonList.add(new Pokemon(29, "Nidoran♀", Types.POISON));
        pokemonList.add(new Pokemon(30, "Nidorina", Types.POISON));
        pokemonList.add(new Pokemon(31, "Nidoqueen", Types.POISON, Types.GROUND));
        pokemonList.add(new Pokemon(32, "Nidoran♂", Types.POISON));
        pokemonList.add(new Pokemon(33, "Nidorino", Types.POISON));
        pokemonList.add(new Pokemon(34, "Nidoking", Types.POISON, Types.GROUND));
        pokemonList.add(new Pokemon(35, "Clefairy", Types.NORMAL));
        pokemonList.add(new Pokemon(36, "Clefable", Types.NORMAL));
        pokemonList.add(new Pokemon(37, "Vulpix", Types.FIRE));
        pokemonList.add(new Pokemon(38, "Ninetales", Types.FIRE));
        pokemonList.add(new Pokemon(39, "Jigglypuff", Types.NORMAL));
        pokemonList.add(new Pokemon(40, "Wigglytuff", Types.NORMAL));
        pokemonList.add(new Pokemon(41, "Zubat", Types.POISON, Types.FLYING));
        pokemonList.add(new Pokemon(42, "Golbat", Types.POISON, Types.FLYING));
        pokemonList.add(new Pokemon(43, "Oddish", Types.GRASS, Types.POISON));
        pokemonList.add(new Pokemon(44, "Gloom", Types.GRASS, Types.POISON));
        pokemonList.add(new Pokemon(45, "Vileplume", Types.GRASS, Types.POISON));
        pokemonList.add(new Pokemon(46, "Paras", Types.BUG, Types.GRASS));
        pokemonList.add(new Pokemon(47, "Parasect", Types.BUG, Types.GRASS));
        pokemonList.add(new Pokemon(48, "Venonat", Types.BUG, Types.POISON));
        pokemonList.add(new Pokemon(49, "Venomoth", Types.BUG, Types.POISON));
        pokemonList.add(new Pokemon(50, "Diglett", Types.GROUND));
        pokemonList.add(new Pokemon(51, "Dugtrio", Types.GROUND));
        pokemonList.add(new Pokemon(52, "Meowth", Types.NORMAL));
        pokemonList.add(new Pokemon(53, "Persian", Types.NORMAL));
        pokemonList.add(new Pokemon(54, "Psyduck", Types.WATER));
        pokemonList.add(new Pokemon(55, "Golduck", Types.WATER));
        pokemonList.add(new Pokemon(56, "Mankey", Types.FIGHTING));
        pokemonList.add(new Pokemon(57, "Primeape", Types.FIGHTING));
        pokemonList.add(new Pokemon(58, "Gowlithe", Types.FIRE));
        pokemonList.add(new Pokemon(59, "Arcanine", Types.FIRE));
        pokemonList.add(new Pokemon(60, "Poliwag", Types.WATER));
        pokemonList.add(new Pokemon(61, "Poliwhirl", Types.WATER));
        pokemonList.add(new Pokemon(62, "Poliwrath", Types.WATER, Types.FIGHTING));
        pokemonList.add(new Pokemon(63, "Abra", Types.PSYCHIC));
        pokemonList.add(new Pokemon(64, "Kadabra", Types.PSYCHIC));
        pokemonList.add(new Pokemon(65, "Alakazam", Types.PSYCHIC));
        pokemonList.add(new Pokemon(66, "Machop", Types.FIGHTING));
        pokemonList.add(new Pokemon(67, "Machoke", Types.FIGHTING));
        pokemonList.add(new Pokemon(68, "Machamp", Types.FIGHTING));
        pokemonList.add(new Pokemon(69, "Bellsprout", Types.GRASS, Types.POISON));
        pokemonList.add(new Pokemon(70, "Weepinbell", Types.GRASS, Types.POISON));
        pokemonList.add(new Pokemon(71, "Victreebel", Types.GRASS, Types.POISON));
        pokemonList.add(new Pokemon(72, "Tentacool", Types.WATER, Types.POISON));
        pokemonList.add(new Pokemon(73, "Tentacruel", Types.WATER, Types.POISON));
        pokemonList.add(new Pokemon(74, "Geodude", Types.ROCK, Types.GROUND));
        pokemonList.add(new Pokemon(75, "Graveler", Types.ROCK, Types.GROUND));
        pokemonList.add(new Pokemon(76, "Golem", Types.ROCK, Types.GROUND));
        pokemonList.add(new Pokemon(77, "Ponyta", Types.FIRE));
        pokemonList.add(new Pokemon(78, "Rapidash", Types.FIRE));
        pokemonList.add(new Pokemon(79, "Slowpoke", Types.WATER, Types.PSYCHIC));
        pokemonList.add(new Pokemon(80, "Slowbro", Types.WATER, Types.FIGHTING));
        pokemonList.add(new Pokemon(81, "Magnemite", Types.ELECTRIC, Types.STEEL));
        pokemonList.add(new Pokemon(82, "Magneton", Types.ELECTRIC, Types.STEEL));
        pokemonList.add(new Pokemon(83, "Farfetch'd", Types.NORMAL, Types.FLYING));
        pokemonList.add(new Pokemon(84, "Doduo", Types.NORMAL, Types.FLYING));
        pokemonList.add(new Pokemon(85, "Dodrio", Types.NORMAL, Types.FLYING));
        pokemonList.add(new Pokemon(86, "Seel", Types.WATER));
        pokemonList.add(new Pokemon(87, "Dewgong", Types.WATER, Types.ICE));
        pokemonList.add(new Pokemon(88, "Grimer", Types.POISON));
        pokemonList.add(new Pokemon(89, "Muk", Types.POISON));
        pokemonList.add(new Pokemon(90, "Shellder", Types.WATER));
        pokemonList.add(new Pokemon(91, "Cloyster", Types.WATER, Types.ICE));
        pokemonList.add(new Pokemon(92, "Gastly", Types.GHOST, Types.POISON));
        pokemonList.add(new Pokemon(93, "Haunter", Types.GHOST, Types.POISON));
        pokemonList.add(new Pokemon(94, "Gengar", Types.GHOST, Types.POISON));
        pokemonList.add(new Pokemon(95, "Onix", Types.ROCK, Types.GROUND));
        pokemonList.add(new Pokemon(96, "Drowzee", Types.PSYCHIC));
        pokemonList.add(new Pokemon(97, "Hypno", Types.PSYCHIC));
        pokemonList.add(new Pokemon(98, "Krabby", Types.WATER));
        pokemonList.add(new Pokemon(99, "Kingler", Types.WATER));
        pokemonList.add(new Pokemon(100, "Voltorb", Types.ELECTRIC));
        pokemonList.add(new Pokemon(101, "Electrode", Types.ELECTRIC));
        pokemonList.add(new Pokemon(102, "Exeggcute", Types.GRASS, Types.PSYCHIC));
        pokemonList.add(new Pokemon(103, "Exeggutor", Types.GRASS, Types.PSYCHIC));
        pokemonList.add(new Pokemon(104, "Cubone", Types.GROUND));
        pokemonList.add(new Pokemon(105, "Marowak", Types.GROUND));
        pokemonList.add(new Pokemon(106, "Hitmonlee", Types.FIGHTING));
        pokemonList.add(new Pokemon(107, "Hitmonchan", Types.FIGHTING));
        pokemonList.add(new Pokemon(108, "Lickitung", Types.NORMAL));
        pokemonList.add(new Pokemon(109, "Koffing", Types.POISON));
        pokemonList.add(new Pokemon(110, "Weezing", Types.POISON));
        pokemonList.add(new Pokemon(111, "Rhyhorn", Types.ROCK, Types.GROUND));
        pokemonList.add(new Pokemon(112, "Rhydon", Types.ROCK, Types.GROUND));
        pokemonList.add(new Pokemon(113, "Chansey", Types.NORMAL));
        pokemonList.add(new Pokemon(114, "Tangela", Types.GRASS));
        pokemonList.add(new Pokemon(115, "Kangaskhan", Types.NORMAL));
        pokemonList.add(new Pokemon(116, "Horsea", Types.WATER));
        pokemonList.add(new Pokemon(117, "Seadra", Types.WATER));
        pokemonList.add(new Pokemon(118, "Goldeen", Types.WATER));
        pokemonList.add(new Pokemon(119, "Seaking", Types.WATER));
        pokemonList.add(new Pokemon(120, "Staryu", Types.WATER));
        pokemonList.add(new Pokemon(121, "Starmie", Types.WATER, Types.PSYCHIC));
        pokemonList.add(new Pokemon(122, "Mr. Mime", Types.PSYCHIC));
        pokemonList.add(new Pokemon(123, "Scyther", Types.BUG, Types.FLYING));
        pokemonList.add(new Pokemon(124, "Jynx", Types.ICE, Types.PSYCHIC));
        pokemonList.add(new Pokemon(125, "Electabuzz", Types.ELECTRIC));
        pokemonList.add(new Pokemon(126, "Magmar", Types.FIRE));
        pokemonList.add(new Pokemon(127, "Pinsir", Types.BUG));
        pokemonList.add(new Pokemon(128, "Tauros", Types.NORMAL));
        pokemonList.add(new Pokemon(129, "Magikarp", Types.WATER));
        pokemonList.add(new Pokemon(130, "Gyarados", Types.WATER, Types.FLYING));
        pokemonList.add(new Pokemon(131, "Lapras", Types.WATER, Types.ICE));
        pokemonList.add(new Pokemon(132, "Ditto", Types.NORMAL));
        pokemonList.add(new Pokemon(133, "Eevee", Types.NORMAL));
        pokemonList.add(new Pokemon(134, "Vaporeon", Types.WATER));
        pokemonList.add(new Pokemon(135, "Jolteon", Types.ELECTRIC));
        pokemonList.add(new Pokemon(136, "Flareon", Types.FIRE));
        pokemonList.add(new Pokemon(137, "Porygon", Types.NORMAL));
        pokemonList.add(new Pokemon(138, "Omanyte", Types.ROCK, Types.WATER));
        pokemonList.add(new Pokemon(139, "Omastar", Types.ROCK, Types.WATER));
        pokemonList.add(new Pokemon(140, "Kabuto", Types.ROCK, Types.WATER));
        pokemonList.add(new Pokemon(141, "Kabutops", Types.ROCK, Types.WATER));
        pokemonList.add(new Pokemon(142, "Aerodactyl", Types.ROCK, Types.FLYING));
        pokemonList.add(new Pokemon(143, "Snorlax", Types.NORMAL));
        pokemonList.add(new Pokemon(144, "Articuno", Types.ICE, Types.FLYING));
        pokemonList.add(new Pokemon(145, "Zapdos", Types.ELECTRIC, Types.FLYING));
        pokemonList.add(new Pokemon(146, "Moltres", Types.FIRE, Types.FLYING));
        pokemonList.add(new Pokemon(147, "Dratini", Types.DRAGON));
        pokemonList.add(new Pokemon(148, "Dragonair", Types.DRAGON));
        pokemonList.add(new Pokemon(149, "Dragonite", Types.DRAGON, Types.FLYING));
        pokemonList.add(new Pokemon(150, "Mewtwo", Types.PSYCHIC));
        pokemonList.add(new Pokemon(151, "Mew", Types.PSYCHIC));

        return pokemonList;
    }
}
